# Generated by Django 4.0.3 on 2022-03-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
