# Generated by Django 4.0.3 on 2022-03-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_tourist',
            field=models.BooleanField(default=True),
        ),
    ]
