# Generated by Django 4.0.3 on 2022-03-29 04:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=200)),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('booking_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('package_name', models.CharField(default='', max_length=100)),
                ('departure_date', models.DateField()),
                ('no_of_person', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField()),
                ('Agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
            ],
        ),
    ]
