# Generated by Django 4.0.3 on 2022-05-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_review_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='departure_date',
        ),
    ]
